export const COUNTRIES = [
  "미국",
  "독일",
  "스페인",
  "프랑스",
  "영국",
  "호주",
  "일본",
  "중국",
  "이탈리아",
  "캐나다",
  "아일랜드",
  "태국",
  "포르투갈",
  "뉴질랜드",
  "폴란드",
  "핀란드",
  "오스트리아",
  "스위스",
  "스웨덴",
  "체코",
  "러시아",
  "벨기에",
  "네덜란드",
  "싱가포르",
  "대만",
  "홍콩",
  "베트남",
  "헝가리",
  "덴마크",
  "멕시코",
  "노르웨이",
  "말레이시아",
  "몽골",
  "그리스",
  "슬로베니아",
  "리투아니아",
  "터키",
  "콜롬비아",
  "브루나이",
  "인도",
  "인도네시아",
  "필리핀",
  "브라질",
  "아르헨티나",
  "칠레",
  "페루",
  "남아프리카공화국",
  "이집트",
  "이스라엘",
  "사우디아라비아",
  "아랍에미리트",
  "카타르",
  "쿠웨이트",
  "대한민국",
  "기타",
  "미정"
] as const;

export type Country = typeof COUNTRIES[number];

// 필터링에 사용할 주요 국가들 (홈페이지용)
export const FILTER_COUNTRIES = [
  { value: "all", label: "전체 국가" },
  { value: "미국", label: "미국" },
  { value: "독일", label: "독일" },
  { value: "스페인", label: "스페인" },
  { value: "프랑스", label: "프랑스" },
  { value: "영국", label: "영국" },
  { value: "호주", label: "호주" },
  { value: "일본", label: "일본" },
  { value: "중국", label: "중국" },
  { value: "이탈리아", label: "이탈리아" },
  { value: "캐나다", label: "캐나다" },
  { value: "아일랜드", label: "아일랜드" },
  { value: "태국", label: "태국" },
  { value: "포르투갈", label: "포르투갈" },
  { value: "뉴질랜드", label: "뉴질랜드" },
  { value: "폴란드", label: "폴란드" },
  { value: "핀란드", label: "핀란드" },
  { value: "오스트리아", label: "오스트리아" },
  { value: "스위스", label: "스위스" },
  { value: "스웨덴", label: "스웨덴" },
  { value: "체코", label: "체코" },
  { value: "러시아", label: "러시아" },
  { value: "벨기에", label: "벨기에" },
  { value: "네덜란드", label: "네덜란드" },
  { value: "싱가포르", label: "싱가포르" },
  { value: "대만", label: "대만" },
  { value: "홍콩", label: "홍콩" },
  { value: "베트남", label: "베트남" },
  { value: "헝가리", label: "헝가리" },
  { value: "덴마크", label: "덴마크" },
  { value: "멕시코", label: "멕시코" },
  { value: "노르웨이", label: "노르웨이" },
  { value: "말레이시아", label: "말레이시아" },
  { value: "몽골", label: "몽골" },
  { value: "그리스", label: "그리스" },
  { value: "슬로베니아", label: "슬로베니아" },
  { value: "리투아니아", label: "리투아니아" },
  { value: "터키", label: "터키" },
  { value: "콜롬비아", label: "콜롬비아" },
  { value: "브루나이", label: "브루나이" },
  { value: "인도", label: "인도" },
  { value: "인도네시아", label: "인도네시아" },
  { value: "필리핀", label: "필리핀" },
  { value: "브라질", label: "브라질" },
  { value: "아르헨티나", label: "아르헨티나" },
  { value: "칠레", label: "칠레" },
  { value: "페루", label: "페루" },
  { value: "남아프리카공화국", label: "남아프리카공화국" },
  { value: "이집트", label: "이집트" },
  { value: "이스라엘", label: "이스라엘" },
  { value: "사우디아라비아", label: "사우디아라비아" },
  { value: "아랍에미리트", label: "아랍에미리트" },
  { value: "카타르", label: "카타르" },
  { value: "쿠웨이트", label: "쿠웨이트" },
  { value: "기타", label: "기타" },
  { value: "대한민국", label: "대한민국" }
];

// 환율 지원 통화 목록 (상품 등록용) 
export const CURRENCIES = [
  { code: "KRW", symbol: "₩", name: "대한민국 원" },
  { code: "USD", symbol: "$", name: "미국 달러" },
  { code: "EUR", symbol: "€", name: "유로" },
  { code: "JPY", symbol: "¥", name: "일본 엔" },
  { code: "GBP", symbol: "£", name: "영국 파운드" },
  { code: "CNY", symbol: "¥", name: "중국 위안" },
  { code: "CAD", symbol: "C$", name: "캐나다 달러" },
  { code: "AUD", symbol: "A$", name: "호주 달러" },
  { code: "SGD", symbol: "S$", name: "싱가포르 달러" },
  { code: "HKD", symbol: "HK$", name: "홍콩 달러" },
  { code: "CHF", symbol: "Fr", name: "스위스 프랑" },
  { code: "SEK", symbol: "kr", name: "스웨덴 크로나" },
  { code: "NOK", symbol: "kr", name: "노르웨이 크로네" },
  { code: "DKK", symbol: "kr", name: "덴마크 크로네" }
];